openapi: 3.0.0
info:
  description:
    $ref: ./index-description.md
  version: 1.0.0
  title: Integrated API
  x-logo:
    url: 'https://redocly.github.io/redoc/petstore-logo.png'
    altText: Petstore logo
