name: Build redocly HTML file
on: workflow_dispatch
permissions:
  contents: read
jobs:
  run-redocly-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: sample-api.yaml
          sparse-checkout-cone-mode: false
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      - run: npx -y @redocly/cli build-docs sample-api.yaml -o output/sample-api.html
      - uses: actions/upload-artifact@v3
        with:
          name: sample-apidoc
          path: output/sample-api.html
