name: Build redocly HTML file
on: workflow_dispatch
permissions:
  contents: read
jobs:
  run-redocly-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - run: npx -y @redocly/cli build-docs openapi.yaml -t template.hbs -o output/sample.html
      - uses: actions/upload-artifact@v4
        with:
          name: sample-apidoc
          path: output/sample.html
